// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RapidBootcamp.MigrationDb.RapidDb;

public partial class OrderHeader
{
    public string OrderHeaderId { get; set; }

    public DateTime TransactionDate { get; set; }

    public int WalletId { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Wallet Wallet { get; set; }
}